### ISSUE TITLE
A suggest among testers or generators?

### ISSUE THREAD

**Issue by pacdiv** [Varunram/Awesome-Regex-Resources#6]
Hi there,

I open an issue to suggest you a new open source tool to write regular expressions.

It's called RegexGuide and it helps beginners to start writing regular expressions through plain English sentences. You can test it [here](https://regex.guide).

If you think it could fit among testers or generators from your list, feel free to post a link to it.

Either way, keep up the good work!

Thanks! ✌️

**Comment by Varunram** [comment]
Thanks @pacdiv for the link, added this in https://github.com/Varunram/Awesome-Regex-Resources/commit/d8fd6c68e1b5734dbb692371101d3dd3da121db1
